#!/bin/bash
set -euo pipefail

info() {
  printf "[\033[00;34mINFO\033[0m] $1\n"
}

success() {
  printf "[\033[00;32mOK\033[0m] $1\n"
}

error() {
  printf "[\033[00;31mERROR\033[0m] $1\n"
}

big_info() {
  printf "\e[34m
==============================
$1
==============================\n\e[m"
}

bootstrap() {
  info "setup"

  initial_setup

  # 以下同じマシンで複数回走らせて問題ない
  info "start install tools"
  install_all

  info "download Makefile"
  download_makefile

  info "download deploy script"
  download_deploy_script

  # ifstat: ネットワークの帯域を確認するためのもの
  sudo apt-get install -y ifstat gpg net-tools golang-go
  check

  info "script Done!"

}

initial_setup() {
  echo "Run Initial Setup?(y/n): "
  read answer

  if [ "$answer" = "n" ]; then
    echo "Skipped!"
    return 0
  fi

  setup

  setup_util

  info "start git init"
  git_init

  info "start git config"
  git_config
}

setup() {
  mkdir -p $HOME/config
  MYSQL_CONF=/etc/mysql

  sudo cp -a $MYSQL_CONF $HOME/config/mysql
  sudo rm -rf $MYSQL_CONF
  sudo ln -sf $HOME/config/mysql /etc

  NGINX_CONF=/etc/nginx

  sudo cp -a $NGINX_CONF $HOME/config/nginx
  sudo rm -rf $NGINX_CONF
  sudo ln -sf $HOME/config/nginx /etc

  sudo chown -R $(whoami) config/
}

setup_util() {
  # SSH接続を切られないようにする
  echo "ClientAliveInterval 60" | sudo tee -a /etc/ssh/sshd_config
  echo "ClientAliveCountMax 3" | sudo tee -a /etc/ssh/sshd_config
  # sudo systemctl restart ssh.service
}

git_config() {
  git config --global user.email "hahihu314+github@gmail.com"
  git config --global user.name "rerost"

  git config --global core.editor 'vim -c "set fenc=utf-8"'

  read -p "empty repository. e.g git@github.com:rerost/hogehoge.git: " input
  git remote add origin $input

  echo "Save repository?(y/n): "
  read answer

  if [ "$answer" = "y" ]; then
    info "start save"
    while :
    do
      read -p "Git added (y/n)" input
      if [ "$input" = "y" ]; then
        echo "Continue to setup!"
        break
      elif [ "$input" = "n" ]; then
        echo "Please Add SSH Key."
      fi
    done
    git commit -m "init"
    git push -u origin master
  else
    git fetch origin
  fi
}

install_all() {
  install_alp
  install_pt_query_digest
  install_discocat
  install_html2png
  install_sqldef
  install_chrome
}


install_alp() {
  info 'Installing alp'
  wget https://github.com/tkuchiki/alp/releases/download/v1.0.7/alp_linux_amd64.zip
  unzip alp_linux_amd64.zip
  sudo mv alp /usr/bin/

  rm alp_linux_amd64.zip

  success "install alp"
}

install_slp() {
  info 'Installing slp'
  wget https://github.com/tkuchiki/slp/releases/download/v0.2.1/slp_linux_amd64.tar.gz
  tar -xvf slp_linux_amd64.tar.gz
  sudo mv slp /usr/bin
  success "install slp"
}

install_pt_query_digest() {
  info 'Install pt-query-digest'
  wget https://github.com/percona/percona-toolkit/archive/3.0.5-test.tar.gz
  tar zxvf 3.0.5-test.tar.gz
  sudo mv ./percona-toolkit-3.0.5-test/bin/pt-query-digest /usr/bin/

  rm 3.0.5-test.tar.gz
  rm -rf percona-toolkit-3.0.5-test

  success "install pt-query-digest"
}

install_discocat() {
  info 'Install discocat'

  mkdir tmp_discocat/
  cd tmp_discocat/

  wget https://github.com/rerost/discocat/releases/download/v0.1.1/discocat_Linux_x86_64.tar.gz
  tar zxvf discocat_Linux_x86_64.tar.gz
  sudo mv ./discocat /usr/bin/

  cd -
  rm -rf tmp_discocat/

  success "install discocat"
}

install_html2png() {
  info 'Install html2png'

  mkdir tmp_html2png/
  cd tmp_html2png/

  wget https://github.com/rerost/html2png/releases/download/v0.1.0/html2png_Linux_x86_64.tar.gz
  tar zxvf html2png_Linux_x86_64.tar.gz
  sudo mv ./html2png /usr/bin/

  cd -
  rm -rf tmp_html2png/

  success "install html2png"
}

install_pprotein() {
  info 'Install pprotein'

  sudo apt install -y graphviz gv
  wget https://github.com/kaz/pprotein/releases/download/v1.2.4/pprotein_1.2.4_linux_amd64.tar.gz
  tar -xvf pprotein_1.2.4_linux_amd64.tar.gz
  sudo cp ~/pprotein /usr/bin/

  success "install pprotein"
}

install_sqldef() {
  info 'Install sqldef'

  wget -O - https://github.com/sqldef/sqldef/releases/latest/download/mysqldef_linux_amd64.tar.gz | tar xvz

  sudo mv ./mysqldef /usr/bin/
  sudo chmod +x /usr/bin/mysqldef

  success "install sqldef"
}

install_chrome() {
  wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
  echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
  sudo apt-get update
  sudo apt-get install -y google-chrome-stable
}

git_init() {
  git init
  git branch -M master
  ssh-keygen -f ~/.ssh/id_rsa && cat ~/.ssh/id_rsa.pub

  printf "\e[34mCopy this SSH key (https://github.com/settings/ssh/new)\e[m\n"
  while :
  do
    read -p "Added SSH key? (y/n)" input
    if [ "$input" = "y" ]; then
      echo "Continue to setup!"
      break
    elif [ "$input" = "n" ]; then
      echo "Please Add SSH Key."
    fi
  done

  set +e
  ssh -T git@github.com
  set -e
}

checking() {
  which $1 > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    success "$1"
  else
    error "$1"
  fi
}

file_check() {
  big_info "file checking!"

  FILES=(bootstrap Makefile deploy deploy_on_remote)

  for f in ${FILES[@]}; do
    if [ -e $f ]; then
      success "$f exists"
    else
      error "$f not exists"
    fi
  done
}

check() {
  big_info "install checking!"

  COMMANDS=(alp pt-query-digest htop discocat)

  for c in ${COMMANDS[@]}; do
    checking $c
  done

  file_check
}

download_makefile() {
  curl -O https://raw.githubusercontent.com/rerost/isucon-magic-powder/refs/heads/master/Makefile
}

download_deploy_script() {
  curl -O https://raw.githubusercontent.com/rerost/isucon-magic-powder/refs/heads/master/deploy
  chmod +x deploy

  curl -O https://raw.githubusercontent.com/rerost/isucon-magic-powder/refs/heads/master/deploy_on_remote
  chmod +x deploy_on_remote
}

bootstrap
