#!/bin/bash
set -euo pipefail

big_info() {
  printf "\e[34m
================================================
$1
================================================\n\e[m"
}

BRANCH=$1

ssh $SSH_OPTION "sudo -u isucon /home/isucon/deploy_on_remote $BRANCH"
