#!/bin/bash
set -euo pipefail

warn() {
  printf "[\033[00;33mWARN\033[0m] $1\n"
}

BRANCH=$1

echo "cd /home/isucon && \
git fetch && \
git stash && \
git checkout $BRANCH && \
git pull origin $BRANCH && \
make bench"

cd /home/isucon && \
git fetch origin && \
git reset --hard origin/master && \
git stash && \
git checkout origin/$BRANCH && \
git pull origin $BRANCH && \
make bench
