name: Test make setup

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Run bootstrap
      run: ./bootstrap
